- 👋 Hi, I’m @Dmoneee
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Dmoneee/Dmoneee is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.

sudo / apt-get install python-pip python-setuptools python-dev cmake
--->
